# Neuron Model and Network Architecture

In [1]:
from IPython.display import Math, display

### 1. The input to single-input neuron is 2.0, its weight is 2.3 and its bias is -3.

    i. What is the net input to the transfer function?

    ii. What is the neuron output?


In [10]:
display(Math(r"i.\ The\ net\ input\ is\ given\ by\ n\ = wp\ + b"))
p = 2
w = 2.3
b = -3

n = w*p + b
print("Net input: n =  {}".format(n))

<IPython.core.display.Math object>

Net input: n =  1.5999999999999996


ii. The output can not be determined because the transfer function is not defined.

### 2. What is the output of the neuron of problem 1 if it has the following transfer functions?

    i. Hard limit
    
    ii. Linear

    iii. Log-sigmoid

In [18]:
# Define the transfer functions
def hardlimit(n):
    if n < 0:
        return 0
    return 1

def linear(n):
    return n

def log_sigmoid(n):
    import numpy as np
    return 1/(1+np.exp(-n))

i. For the hard limit transfer function

In [19]:
a = hardlimit(n)
a

array(1)

ii. For the linear transfer function

In [14]:
a = linear(n)
a

1.5999999999999996

iii. For the log-sigmoid transfer function

In [15]:
a = log_sigmoid(n)
a

0.8320183851339245

### Given a two-input neuron with the following parameters b = 1.2, W = [3 2] and p = [-5 6]^T, calculate the neuron output for the following transfer functions:

    i. A symmetrical hard limit transfer function

    ii. A saturing linear transfer function

    iii. A hyperbolic tangent sigmoid (tansig) transfer function

In [29]:
# Define the transfer functions
def symmetrical_hard_limit(n):
    if n < 0:
        return -1
    return 1

def saturing_linear(n):
    if n < 0:
        a = 0
    elif 0 <= n <= 1:
        a = n
    else:
        a = 1
    return a

def hyperbolic_tangent_sigmoid(n):
    import numpy as np
    return (np.exp(n)-np.exp(-n))/(np.exp(n)+np.exp(-n))



In [24]:
import numpy as np
# We calculate the net input n:
W = np.array([3, 2])
p = np.array([-5,6]).reshape(-1,1)
b = np.array([1.2])

n = np.dot(W,p)+b
n

array([-1.8])

Find the outputs for each of the transfer functions

In [25]:
# i.
a = symmetrical_hard_limit(n)
a

array([-1])

In [27]:
# ii.
a = saturing_linear(n)
a

0

In [30]:
# iii. 
a = hyperbolic_tangent_sigmoid(n)
a

array([-0.94680601])

### iv. A single-layer neural network is to have six inputs and two outputs. The outpus are to be limited to and continuous over the range 0 to 1. What can you tell about the network architecture? Specifically:

    i. How many neurons are required?

    ii. What are the dimensions of the weight matrix?

    iii. What kind of transfer functions could be used?

    iv. Is a bias required?


i. Two neurons, one for each output are required.

ii. The weight matrix has two rows (S = 2 neurons) and six columns (R = 6 inputs). The producto Wp is a two-element vector.

iii. The logsig transfer function would be most appropriate.

iv. Not enough information is given to determine if a bias is required.